### ISSUE TITLE
fnft_clib = ctypes.CDLL(get_lib_path()) -> Could not find module (on Windows 10)

### ISSUE THREAD

**Issue by Yarden92** [xmhk/FNFTpy#3]
I'm trying to run this wrapper on my Windows PC (after successfully running on linux).

I've installed sucessfully the FNFT module, with 160 passed tests.

I've edited the auxilary.py > get_lib_path() function to the following path:
<Desktop>/FNFT/build/libfnft.dll

But I keep getting error on FNFTpy/options_handling.py #46 ```fnft_clib = ctypes.CDLL(get_lib_path())```

the error is:

> FileNotFoundError: Could not find module 'C:\Users\yarde\Desktop\thesis_stuff\thesis\lib\FNFT\build\libfnft.dll' (or one of its dependencies). Try using the full path with constructor syntax.

I'm running Python 3.9.5
I've seen [somewhere](https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python) that since python 3.8 the process for importing DLL has changed..

Not sure how to fix it my own or if its 100% related.

**Comment by xmhk** [comment]
Hi,
I'm not quite sure what the issue is here exactly.
I tried to run the examples and test on my work laptop with windows 10. 

Using Anaconda, I tried different newer python Environments (3.8.10 and 3.9.5). Both work as expected.

I know there often are issues with proper paths on windows. Sometimes the paths are not what is shown to you in the filemanager, and sometimes there is a problem with backslash / slash.

For my testing, I set the **exact and full** path, using **slashes** instead of backslash:    
`libstr = "H:/FNFT/build/libfnft.dll"`
in the auxiliary.py file. 

Maybe you could try that. If that doesn't fix the problem:
can you write here what python environment you use (e.g. WinPython, Anaconda ...)

Best, Christoph

**Comment by Yarden92** [comment]
Thank you for the the quick responae and detailed lookup!
Im using Pycharm (latest up to yesterday), with Python 3.9.5.
I tried to do the exact same thing as you are but still the error, see the attatched screenshot

![image](https://user-images.githubusercontent.com/19271465/123583311-133bc200-d7e8-11eb-8b98-68b61b2145e5.png)

Please let me know which more detail I could provide so we can sort this one out.
Thanks!

**Comment by Yarden92** [comment]
Terminal dis not like it as well..
![image](https://user-images.githubusercontent.com/19271465/123584022-521e4780-d7e9-11eb-96cf-22bb2da4ba0c.png)

**Comment by xmhk** [comment]
Hi Yarden92,

this is weird, Windows behaves really random sometimes. Also it makes things a little complicated to debug, as apparently same versions do not give same results on different machines.

Anyhow, I followed the link you send above about the ctypes DLL issue.
I accordingly made a branch where I modified the calls where the DLL is loaded, 
and added the parameter 'winmode=0'.

Maybe you can try this? You have to pull the repo again and checkout the new branch. 

Initially, you should commit your local changes (most probably to auxiliary.py), because otherwise it will not let you change branches. 

```
git add FNFTpy/auxiliary.py
git commit -m "changed position of DLL in auxiliary.py"
```

Then you pull and checkout:

```
git pull --rebase
git checkout dev_win_cddlbug
```
Now you should be in the different branch. Here, you have to change the position in the auxiliary.py again to the position of the DLL.

To check whether it works, you can run the examples and test:

`python run_examples.py`

I hope this solves the issue.
Best, Christoph

**Comment by Yarden92** [comment]
Yess!! it worked!! nice thank you so much!

**Comment by xmhk** [comment]
Okay, that's great, I hope you can work with this now.
Can you do me a favor? I'm trying to understand what is going on, but unfortunately this seems not to be well documented.
Could you open a python Terminal and run these two lines, and post the output?

```
 import nt
 print(nt._LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR)
```

I'm trying to get what value _LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR has.

Best, Christoph

**Comment by Yarden92** [comment]
Yeah of course, sorry for the delay.

It outputted 256, did I run it correctly?

![image](https://user-images.githubusercontent.com/19271465/124301106-057b9900-db68-11eb-8509-0b763ba2c0c3.png)

**Comment by Yarden92** [comment]
same under pycharm's "Python Console"

**Comment by xmhk** [comment]
Ok, thanks. It's the same here. I was just wandering whether this may be different for you. So it somewhat remains a mystery ...

Best, Christoph
